FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

RUN go install github.com/minio/minio@latest

FROM alpine:latest

COPY --from=builder /go/bin/minio /usr/local/bin/minio

EXPOSE 9000 9001

ENTRYPOINT ["minio"]